apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
      - name: flask-api-server
        image: flask_api_server
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flaskapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: ingress-wildcard-host
    spec:
      rules:
      - host: "local.ecosia.org"
        http:
          paths:
          - pathType: Prefix
            path: "/tree"
            backend:
              service:
                name: flask-service
                port:
                  number: 80
    
